### Chapter 2 Beginning with NumPy fundamentals

### Demonstrates the dtype and shape attributes of ndarray.

In [2]:
import numpy as np

In [3]:
a = np.arange(5)
a.dtype

dtype('int32')

In [4]:
a.shape

(5,)

In [6]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [8]:
m.shape
m.dtype

dtype('int32')

In [9]:
b = np.arange(24).reshape(2, 12)
b.ndim

2

In [10]:
b.size

24

In [11]:
b.itemsize

4

In [12]:
b.nbytes

96

In [13]:
b.dtype

dtype('int32')

In [14]:
b.size * b.itemsize

96

In [15]:
b.resize(6,4)

In [16]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [21]:
b.ndim

1

In [19]:
b = np.arange(5)

In [20]:
b.ndim

1

In [22]:
b

array([0, 1, 2, 3, 4])

In [23]:
b.T

array([0, 1, 2, 3, 4])

In [31]:
b = np.array([1.j + 1, 2.j + 3])

In [32]:
b.imag

array([1., 2.])

In [33]:
b.real

array([1., 3.])

In [27]:
b.dtype

dtype('complex128')

In [28]:
b.dtype.str

'<c16'

In [34]:
b = np.arange(4).reshape(2,2)

In [35]:
f = b.flat

In [36]:
f

In [37]:
for it in f: 
   print(it)

0
1
2
3


In [38]:
b.flat[2]

2

In [39]:
b.flat[[1,3]]

array([1, 3])