### Chapter 2 Beginning with NumPy fundamentals

### Demonstrates multi dimensional arrays slicing.

In [2]:
import numpy as np

### 1D Arrays

In [24]:
a = np.arange(9)

In [25]:
a[3:7]

array([3, 4, 5, 6])

In [26]:
a[:7:2]

array([0, 2, 4, 6])

In [27]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
s = slice(3,7,2)

In [29]:
a[s]

array([3, 5])

In [30]:
s = slice(None, None, -1)

In [31]:
a[s]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

### 2D Arrays

In [3]:
b = np.arange(24).reshape(2,3,4)

In [4]:
b.shape

(2, 3, 4)

In [5]:
b[0,0,0]

0

In [6]:
b[:,0,0]

array([ 0, 12])

In [7]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
b[0, 1]

array([4, 5, 6, 7])

In [12]:
b[0, 1, ::2]

array([4, 6])

In [13]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [14]:
b[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [15]:
b[0, :, 1]

array([1, 5, 9])

In [16]:
b[0,:,-1]

array([ 3,  7, 11])

In [17]:
b[0,::-1, -1]

array([11,  7,  3])

In [18]:
b[0,::2,-1]

array([ 3, 11])

In [19]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [20]:
s = slice(None, None, -1)

In [22]:
s

slice(None, None, -1)

In [23]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
b[(s, s, s)]

array([[[23, 22, 21, 20],
        [19, 18, 17, 16],
        [15, 14, 13, 12]],

       [[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]])