### Chapter 2 Beginning with NumPy fundamentals

### Demonstrates array stacking.

In [2]:
import numpy as np

In [3]:
a = np.arange(9).reshape(3,3)

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
b = 2 * a

In [6]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [8]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [9]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [10]:
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [11]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [13]:
oned = np.arange(2)
twice_oned = 2 * oned

In [14]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [16]:
np.column_stack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [17]:
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [18]:
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [19]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [20]:
np.row_stack((a,b)) == np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])